version: "3.8"
   
services:
  opa:
    image: openpolicyagent/opa:0.40.0-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--authentication=token"
      - "--authorization=basic"
      - "system.rego"
    volumes:
      - type: bind
        source: ./.docker/system.rego
        target: /system.rego

  testrunner:
    build: .
    volumes:
      - .:/app
    depends_on:
      - opa
